# Generated by Django 3.1.7 on 2021-04-04 19:56

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import images.structures
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_id', models.CharField(choices=[('tooth', 'TOOTH'), ('undefined', 'UNDEFINED')], default='undefined', max_length=255)),
                ('surface', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), size=None)),
                ('shape', django.contrib.postgres.fields.jsonb.JSONField(validators=[images.structures.JsonSchemaValidator({'$schema': 'http://json-schema.org/schema#', 'properties': {'endX': {'exclusiveMinimum': 0, 'type': 'integer'}, 'endY': {'exclusiveMinimum': 0, 'type': 'integer'}, 'startX': {'minimum': 0, 'type': 'integer'}, 'startY': {'minimum': 0, 'type': 'integer'}}, 'required': ['endX', 'endY', 'startY', 'startX'], 'type': 'object'})])),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(validators=[images.structures.JsonSchemaValidator({'$schema': 'http://json-schema.org/schema#', 'properties': {'confidence_percent': {'maximum': 100, 'minimum': 0, 'type': 'number'}, 'confirmed': {'type': 'boolean'}}, 'required': ['confirmed', 'confidence_percent'], 'type': 'object'})])),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.annotation')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotation', to='images.image'),
        ),
    ]
